INSERT INTO MSL_PRODUCT 
(weight,    price,      name,               status,     online,     inexpensive,    for_child,  min_age,    professional,   used,   brand_id,   description) values 
(0.09,      25.90,      'Armonica a bocca', true,       true,       false,          false,      null,       false,          false,  14,         'Il grande suono tradizionale di questa armonica blues deriva da un modello MS con corpo in legno, un''ottima scelta per suonare il blues.'),
(1.52,      3999.00,    'Tromba',           true,       true,       true,           false,      null,       true,           true,   1,          'Adams A4 Bb-trumpet, Custom Series, Heavy version, 3 perinet valves, diameter 12,00mm (.470") L- bore, heavy fixed moutphiece thomann receiver, Adams 3ML leadpipe, one piece diameter 14cm (5.5") goldbrass bell, wall thickness: 0,45mm, brushed gold plated, incl. Adams Soft Bag'),
(0.83,      534.38,     'Clarinetto',       true,       false,      false,          false,      null,       false,          false,  2,          'Amati ACL-201 Bb Student Clarinet (Standard)'),
(7.34,      1298.99,    'Sassofono',        true,       false,      true,           false,      null,       false,          false,  2,          'Amati AS43 Intermediate Alto Saxophone Gold Lacquer'),
(1.35,      950.00,     'Tromba',           false,      false,      false,          false,      null,       true,           false,  2,          'Amati Bb-Trumpet Professional ATR 831'),
(2.70,      199.00,     'Trombone',         true,       true,       true,           false,      null,       false,          true,   32,         'An item that has been used previously'),
(10.89,     799.00,     'Corno Francese',   true,       true,       false,          false,      null,       false,          false,  2,          'Single F, Lacquered Brass Body, Rose Brass Leadpipe, mechanical-link tapered rotary valves, nickel-sleeved outer tuning slides, .472" bore, 11.9" bell, wood-frame case (KC-54B)'),
(6.76,      1690.00,    'Basso Tuba',       true,       true,       true,           false,      null,       false,          true,   32,         'Basso tuba argento'),
(31.00,     7500.00,    'Arpa a pedali',    true,       true,       false,          false,      null,       false,          false,  3,          'Its four-fifths size is ideal for the smaller harpist or for the harpist who requires a small, easily portable pedal harp. In terms of string tension and tone it is similar to the larger members of the Etude range.'),
(3.63,      249.99,     'Banjo',            false,      true,       true,           false,      null,       false,          false,  4,          'With a pickup and available in a black chrome finish'),
(7.30,      358.20,     'Tastiera',         true,       true,       true,           false,      null,       true,           false,  5,          'Keylab 61 è una tastiera MIDI a 61 note con tasti sensibili alla velocity e all''aftertouch, progettata per integrarsi alla perfezione in qualsiasi configurazione in studio o live.'),
(9.00,      1488.00,    'Chitarra Acustica',true,       true,       false,          false,      null,       true,           false,  6,          'The Award-Winning Babicz SPIDER model.'),
(0.04,      30.00,      'Clarinetto',       true,       true,       false,          true,       5,          false,          false,  7,          'Clarinetto per bambini'),
(8.40,      2000,       'Sassofono',        true,       true,       false,          false,      null,       true,           false,  8,          'We designed the Big Bell Stone Series Saxophones for you to be able to play without limits, feeling each note vibrate in your hands. The combination of fine hand-engraving and semi-precious natural stone touch pieces from the deep earth make each saxophone an art piece in itself.'),
(1.23,      659,        'Tromba',           false,      true,       true,           false,      null,       true,           true,   8,          'With its sleek design and light bell, the Lynx is the perfect trumpet for "blow your socks off" high notes and zingy, vibrant tone. The new, sleek braces give the trumpet a unique, modern look and are specifically designed to promote free vibration throughout the range of the horn, while improving tone and intonation. '),
(0.60,      89.95,      'Flauto',           true,       true,       false,          false,      null,       true,           true,   8,          'Sterling-silver Royal Crown headjoint, body, & foot; Silver-plated Nickel-silver keys; Open hole; B Foot with Gizmo; Pointed Arms.'),
(3.85,      1109.00,    'Basso',            true,       true,       false,          false,      null,       false,          false,  9,          'Standard 4-String Bass'),
(4.35,      924.00,     'Basso',            false,      false,      false,          false,      null,       false,          false,  9,          '4-String Passive Bolt-On Bass'),
(4.72,      1709.00,    'Basso',            false,      true,       false,          false,      null,       false,          false,  9,          'Icon Standard 6-String Bass'),
(4.54,      1129.00,    'Basso',            true,       true,       false,          false,      null,       false,          false,  9,          'Extended Scale 6-String Bass'),
(14.5,      660.00,     'Tamburo',          true,       true,       false,          false,      null,       true,           false,  10,         'Dynasty MS-XZ14BK DFZ 14" Marching Snare, Black'),
(2.67,      669.00,     'Trombone',         true,       true,       false,          false,      null,       false,          true,   11,         'A brand-new, unused, unopened, undamaged item in its original packaging'),
(0.40,      399.00,     'Flauto',           true,       true,       false,          false,      null,       false,          false,  12,         'The Gemeinhardt 2SP student flute has been a standard and reliable instrument choice for decades and remains the most popular woodwind instrument for beginning flutists'),
(1.26,      1089.00,    'Tromba',           false,      false,      true,           false,      null,       false,          false,  13,         'Getzen 390 Series Student Bb Trumpet'),
(0.69,      349.99,     'Ukulele',          true,       true,       false,          false,      null,       false,          true,   16,         'Plays great, no damage'),
(340.00,    9799.00,    'Piano',            true,       true,       false,          true,       5,          false,          true,   17,         'Kawai baby grand piano');

INSERT INTO MSL_PRODUCT_IMAGES(image, product_id) values
('img/products/p01.jpg',    1),
('img/products/p02a.jpg',   2),
('img/products/p02b.jpg',   2),
('img/products/p02c.jpg',   2),
('img/products/p03.jp',     3),
('img/products/p04.jpg',    4),
('img/products/p05.jpg',    5),
('img/products/p06a.jpg',   6),
('img/products/p06b.jpg',   6),
('img/products/p07.jpg',    7),
('img/products/p08.jpg',    8),
('img/products/p09.jpg',    9),
('img/products/p10.jpg',    10),
('img/products/p11.jpg',    11),
('img/products/p12a.jpg',   12),
('img/products/p12b.jpg',   12),
('img/products/p13.jpg',    13),
('img/products/p14.jpg',    14),
('img/products/p15.jpg',    15),
('img/products/p16.jpg',    16),
('img/products/p17.jpg',    17),
('img/products/p18.jpg',    18),
('img/products/p19.jpg',    19),
('img/products/p20.jpg',    20),
('img/products/p21.jpg',    21),
('img/products/p22.jpg',    22),
('img/products/p23.jpg',    23),
('img/products/p24.jpg',    24),
('img/products/p25.jpg',    25),
('img/products/p26.jpg',    26),
('img/products/p26.jpg',    26);
